services:
  appium-tests:
    image: appium-tests
    build:
      context: .
      dockerfile: AppiumTests/Dockerfile
    environment:
      - TEST_ENV=${TEST_ENV:-Test}
    devices:
      - /dev/kvm:/dev/kvm

  playwright-tests:
    image: playwright-tests
    build:
      context: .
      dockerfile: PlaywrightTests/Dockerfile
    environment:
      - TEST_ENV=${TEST_ENV:-Test}

  api-tests:
    image: api-tests
    build:
      context: .
      dockerfile: ApiTests/Dockerfile
    environment:
      - TEST_ENV=${TEST_ENV:-Test}
